{"name": "test_Create_order_functionality", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <allure_report.TestEcommerce object at 0x0000021F9E672210>\n\n    @pytest.mark.usefixtures()\n    def test_Create_order_functionality(self):\n        print(\"Create Order Functionality checked\")\n>       assert 3==4\nE       assert 3 == 4\n\nallure_report.py:30: AssertionError"}, "start": 1715530898818, "stop": 1715530898819, "uuid": "c9208149-142d-4c41-9da9-aa4bec612821", "historyId": "27f99d1cef0bd711b259c1fcc92d5aa6", "testCaseId": "27f99d1cef0bd711b259c1fcc92d5aa6", "fullName": "allure_report.TestEcommerce#test_Create_order_functionality", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "suite", "value": "allure_report"}, {"name": "subSuite", "value": "TestEcommerce"}, {"name": "host", "value": "Hare_Krishna"}, {"name": "thread", "value": "10632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_report"}]}